name: SCA & SBOM

on:
  push:
    branches: [ dev, test, main ]
  workflow_run:
    workflows: [ "CI/CD" ]
    types: [ "completed" ]

jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with: { java-version: 17, distribution: zulu }

      - name: Build (skip tests)
        run: mvn -B -DskipTests clean package

      - name: Generate SBOM (CycloneDX)
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          output-file: sbom.cdx.json

      - name: Scan via Grype (SARIF)
        uses: anchore/scan-action@v6
        with:
          sbom: sbom.cdx.json
          fail-build: false
          severity-cutoff: high
          only-fixed: true
          output-format: sarif
          output-file: grype.sarif

      - name: Scan via Grype (table)
        uses: anchore/scan-action@v6
        with:
          sbom: sbom.cdx.json
          fail-build: false
          severity-cutoff: high
          only-fixed: true
          output-format: table
          output-file: grype.txt

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: sbom-grype
          path: |
            sbom.cdx.json
            grype.sarif
            grype.txt
